# Generated by Django 5.1.1 on 2024-10-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('school', '0002_jobposting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='submitted', max_length=10)),
                ('cv', models.FileField(blank=True, null=True, upload_to='static/cv_files/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.jobposting')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
    ]
