# Generated by Django 4.2.4 on 2024-10-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_hire_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='cover_letter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
