# Generated by Django 5.1.1 on 2024-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package_customuser_is_subscribed_userpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
