# Generated by Django 5.1.1 on 2024-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_package_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='applied_count',
            field=models.IntegerField(default=0),
        ),
    ]
