# Generated by Django 5.1.1 on 2024-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_school_post_count_teacher_applied_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='offer',
            field=models.JSONField(default=None),
        ),
    ]
