# Generated by Django 5.1.1 on 2024-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_package_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
