# Generated by Django 5.1.1 on 2024-10-05 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_package_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_reset_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_reset_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
