# Generated by Django 5.1.1 on 2024-10-06 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_school_last_reset_date_teacher_last_reset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_reset_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_reset_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
