# Generated by Django 4.2.4 on 2024-10-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
