# Generated by Django 5.1.1 on 2024-10-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_qualifications', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('salary', models.CharField(max_length=50)),
                ('applied_people', models.IntegerField(default=0)),
                ('viewd', models.IntegerField(default=0)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
    ]
