# Generated by Django 5.1.1 on 2024-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed')], default='open', max_length=10),
        ),
    ]
