# Generated by Django 5.1.1 on 2024-10-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_jobposting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
