# Generated by Django 4.2.4 on 2024-10-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_jobposting_school_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='school_logo',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
