"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MSG_LOCALE = "en"

# Allow all origins (for development only)
CORS_ALLOW_ALL_ORIGINS = True

# OR allow specific origins (recommended for production)
# CORS_ALLOWED_ORIGINS = [
#     "https://example.com",
#     "http://localhost:3000",
#     # Add more origins as needed
# ]

# If you want to allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)yn8^q@hhkpao6j82j82#=5#!c%#0glaz4tr&pu3m%i5ei%f#!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.vercel.app',  
    'localhost',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'language',
    'school',
    'teacher',
    'payment',
    'core',
    'stats',
    'corsheaders',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'whitenoise.middleware.WhiteNoiseMiddleware', 

]

ROOT_URLCONF = 'school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

STRIPE_SECRET_KEY = "sk_test_51OdnqTLjmaC4Y7ahrOx1j9hDgzCfU6mRZML3hXa2YhVwl3uESpM8iNv2sWYTiQM6gtzpg0HQmVmlqCQ54nXBfisI007O3KnXGK"
STRIPE_PUBLISHABLE_KEY = "pk_test_51OdnqTLjmaC4Y7ahI8OdKAd0uoWieV0hgmGP3XjIh4aaD46EmPN9Qur0zZjDssbwYugk1mTxKFjkOO3xZjqKmuT3004K0S9DrD"
STRIPE_WEBHOOK_SECRET = 'whsec_2k529W7dtKKkwMnQSTmzRRvbuxImABVR'

SINGLE_PACKAGE_PRICE_ID = 'price_1Q7KV1LjmaC4Y7ahAmofzBPq'
BRONZE_TEACHER_PACKAGE_PRICE_ID = 'price_1Q7WSmLjmaC4Y7ahN3eKETh4'
SILVER_TEACHER_PACKAGE_PRICE_ID = 'price_1Q7WUWLjmaC4Y7ahMMkX1XFi'
GOLD_TEACHER_PACKAGE_PRICE_ID = 'price_1Q7WVdLjmaC4Y7ah80SfV4yI'
BRONZE_SCHOOL_PACKAGE_PRICE_ID = 'price_1Q7WWZLjmaC4Y7ahzYaFV937'
SILVER_SCHOOL_PACKAGE_PRICE_ID = 'price_1Q7WXQLjmaC4Y7ahnZgw73bJ'
GOLD_SCHOOL_PACKAGE_PRICE_ID = 'price_1Q7WYKLjmaC4Y7ahhknGPwja'
TEST_PRICE_ID = 'price_1Q7WZGLjmaC4Y7ah7N8vYIHx'